# Generated by Django 4.2.27 on 2026-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('regdate', models.DateField()),
                ('fullname', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('book', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='xml/')),
                ('scandocs', models.FileField(blank=True, null=True, upload_to='file')),
            ],
        ),
        migrations.DeleteModel(
            name='BirthDocument',
        ),
    ]
