# Generated by Django 4.2.27 on 2026-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0002_birth_delete_birthdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='scandocs',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AddConstraint(
            model_name='birth',
            constraint=models.UniqueConstraint(fields=('regno', 'regdate', 'fullname'), name='uniquebirth'),
        ),
    ]
