# Generated by Django 4.2.27 on 2026-06-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0003_alter_birth_scandocs_birth_uniquebirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formdate', models.DateField()),
                ('issuedto', models.CharField(blank=True, max_length=250, null=True)),
                ('amountpaid', models.FloatField()),
                ('ornumber', models.CharField(blank=True, max_length=10, null=True)),
                ('datepaid', models.DateField()),
                ('verifiedby', models.CharField(blank=True, max_length=250, null=True)),
                ('verifiedbyposition', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='birth.birth')),
            ],
        ),
    ]
