# Generated by Django 4.2.27 on 2026-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0004_form1a'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1a',
            name='Nfather',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='Nmother',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='dateofmarriage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='father',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='mother',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='placeofbirth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='placeofmarriage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
