# Generated by Django 4.2.27 on 2026-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0005_form1a_nfather_form1a_nmother_form1a_dateofmarriage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='dateofmarriage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
