# Generated by Django 4.2.27 on 2026-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0006_alter_form1a_dateofmarriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='datepaid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
