# Generated by Django 4.2.27 on 2026-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0007_alter_form1a_datepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='scandocs',
            field=models.FileField(blank=True, null=True, upload_to='birth/file/'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='birth/xml/'),
        ),
    ]
