# Generated by Django 4.2.27 on 2026-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('regdate', models.DateField()),
                ('fullname', models.CharField(max_length=200)),
                ('dateofdeath', models.DateField()),
                ('book', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='xml/')),
                ('scandocs', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
        migrations.AddConstraint(
            model_name='death',
            constraint=models.UniqueConstraint(fields=('regno', 'regdate', 'fullname'), name='uniquedeath'),
        ),
    ]
