# Generated by Django 4.2.27 on 2026-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='dateofdeath',
            field=models.DateField(blank=True, null=True),
        ),
    ]
