# Generated by Django 4.2.27 on 2026-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0002_alter_death_dateofdeath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='scandocs',
            field=models.FileField(blank=True, null=True, upload_to='death/file/'),
        ),
        migrations.AlterField(
            model_name='death',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='death/xml/'),
        ),
    ]
