# Generated by Django 4.2.27 on 2026-07-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0003_alter_death_scandocs_alter_death_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formdate', models.DateField()),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civilstatus', models.CharField(blank=True, max_length=250, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=250, null=True)),
                ('dateofdeath', models.DateField(blank=True, null=True)),
                ('placeofdeath', models.CharField(blank=True, max_length=250, null=True)),
                ('issuedto', models.CharField(blank=True, max_length=250, null=True)),
                ('amountpaid', models.FloatField()),
                ('ornumber', models.CharField(blank=True, max_length=10, null=True)),
                ('datepaid', models.DateField(blank=True, null=True)),
                ('verifiedby', models.CharField(blank=True, max_length=250, null=True)),
                ('verifiedbyposition', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('death', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='death.death')),
            ],
        ),
    ]
