# Generated by Django 4.2.27 on 2026-07-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0004_form2a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2a',
            name='death',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death', to='death.death'),
        ),
    ]
