# Generated by Django 4.2.27 on 2026-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50, unique=True)),
                ('regdate', models.DateField()),
                ('husband', models.CharField(max_length=250)),
                ('wife', models.CharField(max_length=250)),
                ('dateofmarriage', models.DateField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('book', models.IntegerField(blank=True, null=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='marriage/xml')),
                ('scandocx', models.FileField(blank=True, null=True, upload_to='marriage/file')),
            ],
        ),
    ]
