# Generated by Django 4.2.27 on 2026-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(fields=('regno', 'husband', 'wife'), name='uniquemarriage'),
        ),
    ]
