# Generated by Django 4.2.27 on 2026-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_marriage_uniquemarriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateissue', models.DateField(auto_now=True)),
                ('hname', models.CharField(max_length=250)),
                ('wname', models.CharField(max_length=250)),
                ('hage', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('hsex', models.CharField(max_length=15)),
                ('wsex', models.CharField(max_length=15)),
                ('hcitizen', models.CharField(max_length=15)),
                ('wcitizen', models.CharField(max_length=15)),
                ('hstatus', models.CharField(max_length=15)),
                ('wstatus', models.CharField(max_length=15)),
                ('hfather', models.CharField(max_length=200)),
                ('wfather', models.CharField(max_length=200)),
                ('hmother', models.CharField(max_length=200)),
                ('wmother', models.CharField(max_length=200)),
                ('regno', models.CharField(max_length=15)),
                ('regdate', models.DateField()),
                ('dateofmarriage', models.DateField()),
                ('placeofmarriage', models.DateField()),
                ('issuedto', models.CharField(blank=True, max_length=250, null=True)),
                ('verifyby', models.CharField(blank=True, max_length=250, null=True)),
                ('verifyposition', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('ornumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ordate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
