# Generated by Django 4.2.27 on 2026-07-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0003_form2a'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form2a',
            new_name='Form3a',
        ),
    ]
