# Generated by Django 4.2.27 on 2026-07-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0004_rename_form2a_form3a'),
    ]

    operations = [
        migrations.AddField(
            model_name='form3a',
            name='marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marriage.marriage'),
        ),
    ]
