# Generated by Django 4.2.27 on 2026-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0005_form3a_marriage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form3a',
            old_name='amount',
            new_name='amountpaid',
        ),
        migrations.RenameField(
            model_name='form3a',
            old_name='verifyby',
            new_name='verifiedby',
        ),
        migrations.RenameField(
            model_name='form3a',
            old_name='verifyposition',
            new_name='verifiedbyposition',
        ),
        migrations.AddField(
            model_name='form3a',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
