# Generated by Django 4.2.27 on 2026-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0006_rename_amount_form3a_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3a',
            name='placeofmarriage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
