# Generated by Django 4.2.27 on 2026-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0007_alter_form3a_placeofmarriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='form3a',
            name='book',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form3a',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
